- name: Launch back
  docker_container:
    name: back
    image: avidal373/backend:latest
    pull: true
    recreate: true
    ports:
      - "8080:8080"
    networks: 
      - name: app-network
      
  vars:
    ansible_python_interpreter: /usr/bin/python3


