name: Continuous Deployment

on:
    #to begin you want to launch this job in main and develop
    push:
      branches: 
        - main
        - develop
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version


    - name: Build image and push front
      uses: docker/build-push-action@v3
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./ansible
        # Note: tags has to be all lower-case
        tags:  ${{secrets.DOCKERHUB_USERNAME}}/ansible:latest
        push: ${{ github.ref == 'refs/heads/main' }}
    

    - name: Set up Ansible and Vault
      run: |
        docker pull ansible:latest
        docker run -it --rm -v $(pwd):/ansible -e VAULT_PASSWORD="${{ secrets.VAULT_PASSWORD }}" ansible:latest
        cd /ansible

    - name: Decrypt encrypted private key
      run: ansible-vault decrypt vault-encrypted-key --output vault-decrypted-key

    - name: SSH to the server and deploy
      run: |
        chmod 600 vault-decrypted-key
        ssh -i vault-decrypted-key user@server_ip "cd /backend && git pull && docker-compose up -d"

    - name: Clean up
      run: |
        rm -f vault-decrypted-key
